- name: instala pacote server
  package:
    name: puppetserver 
    update_cache: yes
  when: ansible_hostname == "devops"

- name: instala pacote agent
  package: 
    name: puppet-agent
    update_cache: yes
