- name: instala pacote server
  package:
    name: puppetserver
    state: present
    update_cache: yes
  when: ansible_hostname == "DevOps"

- name: instala pacote agent
  package: 
    name: puppet-agent
    state: present
    update-cache: yes
